[alembic]
script_location = alembic
# Supabase (Transaction pooler) SQLAlchemy URL
sqlalchemy.url = postgresql+psycopg://postgres.[PROJECT-REF]:[PASSWORD]@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
